### ISSUE TITLE
ignore expand_keywords after reindex

### ISSUE THREAD

**Issue by savage4pro** [manticoresoftware/docker#1]
reindex just after saving config file:
![normal behaviour](https://monosnap.com/file/aoNHQPatUKtPUr4R4Ww042kT9krOBt.png)
but next reindex breaks results:
![expand_keywords ignored](https://monosnap.com/file/ef8kN0WOwqZ3kxIqdWwsOrZZv0cEiH.png)

possible ref: https://github.com/manticoresoftware/manticoresearch/issues/70

temporary workaround:
![костыль](https://monosnap.com/file/EQTqF45jTsEj6O7s90LixKF2VYtpKj.png)

**Comment by tomatolog** [comment]
should be fixed at matmanticoresoftware/manticoresearch@546e2297a01cc2913bc0d33052d5bcefae8737eb and published at next release
