### ISSUE TITLE
too many ports EXPOSEd in Dockerfile - incompatibility with GitLab CI

### ISSUE THREAD

**Issue by someniatko** [manticoresoftware/docker#14]
I try to use this image as a [service in GitLab CI](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service).
The behaviour of Gitlab CI is such that it looks up the ports EXPOSEd and checks if they are available. Unfortunately, this image's Dockerfile tells that it EXPOSEs ports 9306, 9308, 9312, and, for some reason, 9315-9325. Of course it doesn't actually listen on those 9315-9325 ports, therefore fails the GitLab's check. 

Unfortunately [it is not possible to "unexpose" ports using a child image](https://github.com/moby/moby/issues/3465) (`FROM manticoresearch/manticore` in Dockerfile), the only option I am left with is completely forking the project, which i would like to avoid.

Is it really necessary to keep this `EXPOSE 9315-9325` statement in the Dockerfile? The image users can always bind any port using `docker run -p ...` option.

**Comment by sanikolaev** [comment]
Good point. Indeed we might not need the EXPOSE rules, especially for the replication ports (9315-9325). We'll discuss it in the team.

**Comment by manticoresearch** [comment]
Fixed in https://github.com/manticoresoftware/docker/commit/1a58d367feb0c43ad4f136261e4804c2756d3f0c
