### ISSUE TITLE
Incorrect docker mount point

### ISSUE THREAD

**Issue by lehha** [manticoresoftware/docker#16]
In README.md instruction mount point for data is incorrect:
$(pwd)/data:/var/lib/manticore/data/
https://github.com/manticoresoftware/docker/blob/355202bf0757dfcb0d0cba850f8ae6905b666ea0/README.md?plain=1#L51

Manticore stores data in /var/lib/manticore/, so documented mountpoint not working.

**Comment by sanikolaev** [comment]
Thank you! Fixed.
