### ISSUE TITLE
Is there an example or demo that shows how to deploy manticoresearch on multiple servers(machines)?

### ISSUE THREAD

**Issue by axhiao** [manticoresoftware/docker#24]

**Comment by sanikolaev** [comment]
For the docker image - I'm afraid not, but perhaps these links will be helpful:
* https://play.manticoresearch.com/replication - interactive course about Manticore replication
* https://manual.manticoresearch.com/Creating_a_cluster/Setting_up_replication/Creating_a_replication_cluster#Creating-a-replication-cluster - about creating and joining a replication cluster
* https://manual.manticoresearch.com/Server_settings/Searchd#listen - about `listen = ...:replication`

Docker is just a wrapper for Manticore Search in this case, what's needed on top of what Manticore does is to just make replication ports accessible.

**Comment by axhiao** [comment]
ok. got it. thank you for your response!
