### ISSUE TITLE
Backups in Docker

### ISSUE THREAD

**Issue by mtruyens** [manticoresoftware/docker#44]
Unless if I'm missing something, the current instructions do not indicate how to restore a backup when using Docker. Simply running 

```docker exec -it CONTAINER-ID /usr/bin/manticore-backup --backup-dir=... --restore=....```

does not work, because searchd will then be running within the Dockter container, which is not allowed during restore :-(

Thanks for your help!

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch-backup/issues/77 ("support shebang config")

**Comment by sanikolaev** [comment]
As discussed on today's call here's what the backup/restore functionality in the official docker can look like in general:

## Backup

Just make sure `manticore-backup` works fine via `docker exec` inside the container, the rest is up to the user

## Restore

1. Put your backup into some dir 
2. Mount your dir with a backup to `backup` inside the container like `docker run ... -v ...:/backup/`
3. The entrypoint script will detect it automatically, will restore from the backup and will stop the container, so you can start it normally without mapping the backup dir, which would be trigger for ther user to not forget to do it, so they don't nuke down their data accidentally. Also, some confirmation may make sense as well before restoring for the same reason.

**Comment by sanikolaev** [comment]
> Blocked by https://github.com/manticoresoftware/manticoresearch-backup/issues/77 ("support shebang config")

Done. We can go ahead with this issue.

**Comment by djklim87** [comment]
Blocked by

- [ ] https://github.com/manticoresoftware/manticoresearch-backup/issues/83
- [ ] https://github.com/manticoresoftware/manticoresearch-backup/issues/84

**Comment by djklim87** [comment]
Blocked by

- [ ] https://github.com/manticoresoftware/manticoresearch-backup/issues/88

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/docker/pull/54
