### ISSUE TITLE
Ideas for more tests

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#52]
The task is to prepare ideas for more tests. I'll start:
* [x] Test the one-liner from the docs https://github.com/manticoresoftware/docker#quick-usage
* [x] EXTRA=0/1
* [x]  QUERY_LOG_TO_STDOUT=true
* [ ]  indexing via `docker exec -it manticore gosu manticore indexer --all --rotate`
* [ ]  startup flags https://github.com/manticoresoftware/docker#startup-flags : make sure they get delivered to the searchd
* [ ]  running under non-root - https://github.com/manticoresoftware/docker#running-under-non-root
* [ ]  building plain tables - https://github.com/manticoresoftware/docker#building-plain-tables
* [ ]  configuring searchd via env. vars - https://github.com/manticoresoftware/docker#configuring-manticore-search-with-docker

Once we are done with the ideas let's create another task to implement them, perhaps they should be grouped into a few issues.

**Comment by djklim87** [comment]
* MCL=0/1
* backups
* update versions (in case you have old version of extra packages and you trying update to new searchd version)

**Comment by sanikolaev** [comment]
* Flexible env. vars (may have been already done).

**Comment by sanikolaev** [comment]
Closing as done. This issue is now used as a checklist of separate tasks that are to be created to cover each of the above mentioned items.
