### ISSUE TITLE
Test: one-liner

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#57]
Test the one-liner from the docs https://github.com/manticoresoftware/docker#quick-usage. Make sure the one-liner works as expected with the dev version.

**Comment by PavelShilin89** [comment]
@sanikolaev The test does not run, I think because the command has the `-it` flag. Everything hangs on it and waits for further command inside mysql.
I can of course redo the command, or break it into parts. But I decided to clarify, how do you want it to be tested?

**Comment by sanikolaev** [comment]
It's ok to modify the command to make it work in the testing environment.

**Comment by PavelShilin89** [comment]
Done https://github.com/manticoresoftware/docker/pull/62

**Comment by sanikolaev** [comment]
> Done https://github.com/manticoresoftware/docker/pull/62

Merged.
