### ISSUE TITLE
Test: EXTRA=0/1

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#58]
Create a test to make sure the `EXTRA` env. var. works as expected: 
- installs the extra packages and makes them accessible in Manticore when used (`searchd -v` should be enough)
  - doesn't install them again when the container is started again (as it caches them)
- does not install them when not used

**Comment by PavelShilin89** [comment]
Done https://github.com/manticoresoftware/docker/pull/64

**Comment by sanikolaev** [comment]
Requested changes.

**Comment by PavelShilin89** [comment]
Done

**Comment by sanikolaev** [comment]
Requested changes.

**Comment by PavelShilin89** [comment]
Completely fixed

**Comment by sanikolaev** [comment]
Requested changes.

**Comment by sanikolaev** [comment]
PR merged
