### ISSUE TITLE
Test: QUERY_LOG_TO_STDOUT=true

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#59]
Create a test that covers the `QUERY_LOG_TO_STDOUT=true` behaviour.

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/docker/pull/60

**Comment by sanikolaev** [comment]
Please comment https://github.com/manticoresoftware/docker/pull/60#discussion_r1405617183

**Comment by sanikolaev** [comment]
Still no comment here https://github.com/manticoresoftware/docker/pull/60#discussion_r1405617183

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/docker/pull/65/files

**Comment by sanikolaev** [comment]
`timeout 5` is not much better than `sleep 5`. What I meant is that the test can be more robust if you used a longer timeout, but the command would end as soon as the event occurs. E.g. like here https://github.com/manticoresoftware/manticoresearch/blob/master/test/clt-tests/logstash/logstash-dev.rec#L63

**Comment by PavelShilin89** [comment]
Will that be enough? `Timeout 60 docker logs -f manticore | grep -qm1 "accepting connections" && echo 'accepting connections' || echo 'Timeout failed'`

**Comment by sanikolaev** [comment]
> Will that be enough? Timeout 60

I think yes.

**Comment by PavelShilin89** [comment]
@sanikolaev In this pull request https://github.com/manticoresoftware/docker/pull/66/files I increased the timeout time as suggested above. Please check and do the merge.

**Comment by sanikolaev** [comment]
<img width="1027" alt="image" src="https://github.com/manticoresoftware/docker/assets/28719845/5665c955-d565-4978-86a1-9388b22ff876">

Please fix.

**Comment by sanikolaev** [comment]
Approved. Please merge and close unless it breaks in the master branch.
