### ISSUE TITLE
Tests for https://github.com/manticoresoftware/docker?tab=readme-ov-file#backup-and-restore

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#78]
Let's add CLT tests for https://github.com/manticoresoftware/docker?tab=readme-ov-file#backup-and-restore

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/docker/issues/79

**Comment by manticoresearch** [comment]
> Blocked by https://github.com/manticoresoftware/docker/issues/79

Unblocked.

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/docker/pull/89
