### ISSUE TITLE
Test Postgres + Docker

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/docker#88]
### Proposal:

I prepared a test case to test Postgres with Docker, which looks more like what can be in production, compared to this [test](https://github.com/manticoresoftware/docker/blob/master/clt_tests/tests/plain-indexes-all.rec). You can find the discussion and test case here: https://github.com/manticoresoftware/manticoresearch/discussions/1801#discussioncomment-9824303.

Let's make a CLT test from it.

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [x] Tests developed

</details>

**Comment by PavelShilin89** [comment]
Blocked by https://github.com/manticoresoftware/repomanager/issues/32

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/docker/pull/93
