### ISSUE TITLE
Not all files cleaned up with EXTRA=1

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/docker#99]
### Bug Description:

We have an issue when we run a Docker container from our official image with the EXTRA=1 flag, and some files are not cleaned up after installation. We should clean them up because it's useless to keep them inside the container.

**MRE**

Run the latest image:

```bash
docker run --env EXTRA=1 --name mre -it --rm manticoresearch/manticore:dev-6.3.9-a71989f
```
Investigate what is inside after all is done:

```bash
➜  ~  docker exec -it mre bash
root@2214c1cedb7d:/var/lib/manticore# ls -lt .extra/
total 112332
-rwxr-xr-x 1 manticore manticore 74910048 Dec  6 05:00 manticore-executor
-rw-r--r-- 1 manticore manticore      488 Dec  6 05:00 _gpgorigin
-rw-r--r-- 1 manticore manticore 20045388 Dec  6 05:00 data.tar.xz
-rw-r--r-- 1 manticore manticore      608 Dec  6 05:00 control.tar.xz
-rw-r--r-- 1 manticore manticore        4 Dec  6 05:00 debian-binary
-rw-r--r-- 1 manticore manticore 20046736 Nov 24 09:18 manticore-executor_1.2.1-24112407-aedd870_arm64.deb
drwxr-xr-x 3 manticore manticore     4096 Nov 24 09:08 usr
root@2214c1cedb7d:/var/lib/manticore# ls -lt /tmp/
total 8
drwxr-xr-x 3 manticore manticore 4096 Dec  6 05:00 galera
drwxr-xr-x 3 manticore manticore 4096 Dec  6 05:00 columnar
root@2214c1cedb7d:/var/lib/manticore# du -sh /tmp
16M	/tmp
root@2214c1cedb7d:/var/lib/manticore# du -sh .extra
182M	.extra
root@2214c1cedb7d:/var/lib/manticore#
```

### Docker image version:

Latest dev version

### Have you tried the latest development version?

None

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/docker/pull/100
